# Generated by Django 6.0.3 on 2026-04-13 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_product_sale_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('employee', 'Employee')], max_length=50),
        ),
    ]
